-- Migration 120: project_files.edit_mode
--
-- RENUMBERED FROM 106. This file is byte-identical in effect to the old
-- 106_project_files_edit_mode.sql; only its number changed.
--
-- Why: two files claimed version 106 -- this one and
-- 106_agent_notifications.sql. Both landed in the production DB before
-- the collision checker existed, so _discover_migrations tolerates the
-- pair *iff every colliding filename is already in schema_version*
-- (migrator.py). That condition holds only on a DB that already has
-- them. On a FRESH database schema_version is empty, the tolerance does
-- not apply, and the migrator raises
--
--   RuntimeError: Migration version collision at 106: [...]
--
-- before doing anything else. That is why the pytest suite could not be
-- collected at all: every test DB is fresh, so all 170 errors traced to
-- this one filename clash. Renaming is the fix the error message itself
-- asks for.
--
-- 120 rather than a slot adjacent to 106 because integers leave no room
-- between 106 and 107. Moving it later is safe: the column it adds is
-- referenced by no other migration (checked across the whole
-- migrations/ tree), nothing recreates project_files after its original
-- definition, and no migration does SELECT * against it -- so no
-- ordering dependency exists to break.
--
-- EXISTING DATABASES: this migration must NOT re-run; the column is
-- already there and ALTER TABLE ADD COLUMN would fail with "duplicate
-- column name: edit_mode". The migrator snapshots schema_version once
-- before its loop, so a migration cannot rewrite its own bookkeeping
-- mid-run. Point the record at the new filename by hand, once, before
-- migrating:
--
--   UPDATE schema_version
--      SET version = 120, filename = '120_project_files_edit_mode.sql'
--    WHERE filename = '106_project_files_edit_mode.sql';
--
-- Fresh databases need nothing: the fresh path applies schema.sql and
-- marks numbered migrations applied without executing them.
--
-- ---------------------------------------------------------------------
-- Original header follows.
--
-- Motivation: currently every file goes through the full deploy chain
-- (DB → checkout → git → nix flake → home-manager overlay → nix
-- store → symlink into ~). For rarely-edited files this is correct.
-- For files under active development (Emacs .el files, config
-- fragments), it means every edit is a 90-second rebuild cycle.
--
-- Rather than a global `templedb.devMode` nix flag that toggles all
-- edit-mode-eligible files at once, each file carries its own
-- edit_mode attribute. Consumers (home.nix generators, publish,
-- doctor) filter on it.
--
-- Values (documented, not enforced by CHECK):
--   'immutable'    — default, current behavior. File flows through
--                    the full DB → checkout → nix chain.
--   'hot-reload'   — file is materialized through the chain, but
--                    home.nix skips it for its own overlays.
--                    Consumers reload from the checkout at use time
--                    (e.g. an Emacs `M-x eval-buffer`).
--   'live-symlink' — home.nix generates a symlink to the FUSE mount
--                    at ~/temple/<slug>/<path> instead of copying.
--                    Edits reflect immediately without a rebuild.
--                    Requires the FUSE mount to be active; doctor
--                    invariant will report drift if not.
--
-- Nullable; NULL treated as 'immutable' for backward compat.
--
-- Design: reports/2026-09-19-2012-declarative-reframe-*.html §6.

ALTER TABLE project_files ADD COLUMN edit_mode TEXT;

-- Fast lookup for "give me all live-symlink files in this project"
-- (used by the home.nix generator).
CREATE INDEX IF NOT EXISTS idx_project_files_edit_mode
    ON project_files(project_id, edit_mode)
    WHERE edit_mode IS NOT NULL AND edit_mode != 'immutable';
