#!/usr/bin/env python3
"""
NixOS integration commands for TempleDB.

Self-contained — no nix store patch loading needed.
Includes dirty-state tracking, auto-generated file headers,
and status/edit-template subcommands.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from cli.core import Command
from logger import get_logger

logger = get_logger(__name__)


# ── Keys that are never considered "pending changes" ──────────────────────────

_TRACKING_KEYS = ("nixos.last_generated_at", "nixos.last_generated_snapshot")


# ── DB helpers ────────────────────────────────────────────────────────────────

def _get_conn():
    from db_utils import get_connection
    return get_connection()


def _dirty_count(conn) -> int:
    try:
        row = conn.execute(
            "SELECT value FROM system_config WHERE key = 'nixos.last_generated_at'"
        ).fetchone()
        placeholders = ",".join("?" * len(_TRACKING_KEYS))
        if not row:
            return conn.execute(
                f"SELECT COUNT(*) FROM system_config WHERE key NOT IN ({placeholders})",
                _TRACKING_KEYS,
            ).fetchone()[0]
        return conn.execute(
            f"SELECT COUNT(*) FROM system_config "
            f"WHERE key NOT IN ({placeholders}) AND updated_at > ?",
            (*_TRACKING_KEYS, row[0]),
        ).fetchone()[0]
    except Exception:
        return 0


def _mark_clean():
    """Record that generate just ran — saves snapshot and clears dirty state."""
    try:
        from db_utils import execute, get_connection
        conn = get_connection()
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
        placeholders = ",".join("?" * len(_TRACKING_KEYS))
        rows = conn.execute(
            f"SELECT key, value FROM system_config WHERE key NOT IN ({placeholders})",
            _TRACKING_KEYS,
        ).fetchall()
        snapshot = {r[0]: r[1] for r in rows}
        execute(
            "INSERT INTO system_config (key, value, description, updated_at) "
            "VALUES ('nixos.last_generated_at', ?, "
            "        'Timestamp of last successful nixos generate', ?) "
            "ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at",
            (now, now),
        )
        execute(
            "INSERT INTO system_config (key, value, description, updated_at) "
            "VALUES ('nixos.last_generated_snapshot', ?, "
            "        'system_config snapshot at last generate', ?) "
            "ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at",
            (json.dumps(snapshot), now),
        )
    except Exception:
        pass


def _check_dirty_and_prompt() -> bool:
    """Return True if the caller should proceed, False if aborted."""
    conn = _get_conn()
    count = _dirty_count(conn)
    if count == 0:
        return True
    try:
        row = conn.execute(
            "SELECT slug FROM projects WHERE project_type = 'nixos-config' LIMIT 1"
        ).fetchone()
        slug = row[0] if row else "system_config"
    except Exception:
        slug = "system_config"

    noun = "config key" if count == 1 else "config keys"
    print(f"⚠ {count} {noun} changed since last generate.", file=sys.stderr)
    try:
        answer = input("Generate now? [Y/n] ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print("\nCancelled.", file=sys.stderr)
        return False

    if answer in ("", "y", "yes"):
        import subprocess
        launcher = Path(__file__).parent.parent.parent.parent / "templedb"
        result = subprocess.run([str(launcher), "nixos", "generate", slug])
        if result.returncode != 0:
            print("⚠ Generate failed — continuing with rebuild anyway.", file=sys.stderr)
        else:
            _mark_clean()
    else:
        print("Skipping generate — rebuild may use stale config.", file=sys.stderr)
    return True


# ── Generated file header ─────────────────────────────────────────────────────

_HEADER_TEMPLATE = """\
# AUTO-GENERATED by TempleDB — do not edit manually.
# Source: templedb nixos config keys (system_config table)
# Generated: {timestamp}
# To update:
#   templedb var set <key> <value> --nixos
#   templedb nixos generate {slug}
"""


def _with_header(text: str, slug: str) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
    header = _HEADER_TEMPLATE.format(timestamp=timestamp, slug=slug)
    if "AUTO-GENERATED by TempleDB" in text:
        lines = text.splitlines(keepends=True)
        i = 0
        in_header = False
        while i < len(lines):
            if "AUTO-GENERATED by TempleDB" in lines[i]:
                in_header = True
            if in_header and not lines[i].startswith("#") and lines[i].strip():
                break
            i += 1
        text = "".join(lines[i:])
    return header + "\n" + text


# ── Slug resolution ───────────────────────────────────────────────────────────

def _all_nixos_slugs(conn):
    rows = conn.execute(
        "SELECT slug FROM projects WHERE project_type = 'nixos-config' ORDER BY slug"
    ).fetchall()
    return [r[0] for r in rows]


def _resolve_slug(slug_arg) -> str | None:
    conn = _get_conn()
    all_slugs = _all_nixos_slugs(conn)
    if not all_slugs:
        print("No nixos-config projects found. Register one with:", file=sys.stderr)
        print("  templedb nixos set-type <project-slug>", file=sys.stderr)
        return None
    if slug_arg:
        if slug_arg in all_slugs:
            return slug_arg
        print(f"Unknown nixos-config project: '{slug_arg}'", file=sys.stderr)
        for s in all_slugs:
            print(f"  {s}", file=sys.stderr)
        return None
    if len(all_slugs) == 1:
        return all_slugs[0]
    print("Multiple nixos-config projects found. Specify one:", file=sys.stderr)
    for s in all_slugs:
        print(f"  {s}", file=sys.stderr)
    return None


# ── Status display ────────────────────────────────────────────────────────────

def _fmt_ts(ts: str) -> str:
    return ts[:16] if ts else "never"


def _nixos_status(slug: str):
    conn = _get_conn()
    gen_row = conn.execute(
        "SELECT value FROM system_config WHERE key = 'nixos.last_generated_at'"
    ).fetchone()
    last_gen = gen_row[0] if gen_row else None

    snap_row = conn.execute(
        "SELECT value FROM system_config WHERE key = 'nixos.last_generated_snapshot'"
    ).fetchone()
    snapshot = json.loads(snap_row[0]) if snap_row else {}

    last_rebuild = None
    proj_row = conn.execute("SELECT id FROM projects WHERE slug = ?", (slug,)).fetchone()
    if proj_row:
        rb_row = conn.execute(
            "SELECT deployed_at FROM system_deployments "
            "WHERE project_id = ? AND exit_code = 0 "
            "ORDER BY deployed_at DESC LIMIT 1",
            (proj_row[0],),
        ).fetchone()
        if rb_row:
            last_rebuild = rb_row[0]

    placeholders = ",".join("?" * len(_TRACKING_KEYS))
    if last_gen:
        pending_rows = conn.execute(
            f"SELECT key, value FROM system_config "
            f"WHERE key NOT IN ({placeholders}) AND updated_at > ? ORDER BY key",
            (*_TRACKING_KEYS, last_gen),
        ).fetchall()
    else:
        pending_rows = conn.execute(
            f"SELECT key, value FROM system_config "
            f"WHERE key NOT IN ({placeholders}) ORDER BY key",
            _TRACKING_KEYS,
        ).fetchall()

    pending = [(r[0], r[1]) for r in pending_rows]
    count = len(pending)

    if last_gen is None:
        live_status = "UNKNOWN (never generated)"
    elif last_rebuild is None:
        live_status = "BEHIND (never rebuilt)"
    elif last_gen > last_rebuild:
        live_status = "BEHIND (rebuild needed)"
    else:
        live_status = "UP TO DATE"

    # Migration status
    migration_status = "?"
    try:
        from migrator import Migrator
        from db_utils import DB_PATH
        m = Migrator(DB_PATH)
        status_entries = m.status()
        pending_migrations = sum(1 for s in status_entries if not s["applied"])
        if pending_migrations == 0:
            migration_status = "OK"
        else:
            migration_status = f"{pending_migrations} PENDING — run: templedb db migrate"
    except Exception:
        migration_status = "unknown"

    print()
    print(f"  Migrations:    {migration_status}")
    if count > 0:
        noun = "change" if count == 1 else "changes"
        since = f" since last generate ({_fmt_ts(last_gen)})" if last_gen else ""
        print(f"  Config keys:   {count} pending {noun}{since}")
    else:
        print(f"  Config keys:   up to date")
    print(f"  Last generate: {_fmt_ts(last_gen)}")
    print(f"  Last rebuild:  {_fmt_ts(last_rebuild)}")
    print(f"  Live system:   {live_status}")

    if pending:
        print()
        print("  Pending changes:")
        key_w = max(len(k) for k, _ in pending)
        for key, new_val in pending:
            old_val = snapshot.get(key)
            if old_val is None:
                change = f"(new) {new_val}"
            elif old_val == new_val:
                change = f"{old_val}  (touched)"
            else:
                change = f"{old_val} → {new_val}"
            print(f"    {key:{key_w}}  {change}")

    needs_generate = count > 0
    needs_rebuild = last_gen is None or last_rebuild is None or last_gen > last_rebuild
    if needs_generate or needs_rebuild:
        print()
        print("  Next steps:")
        if needs_generate:
            print(f"    templedb nixos generate {slug}")
        if needs_rebuild:
            print(f"    templedb nixos rebuild  {slug}")
    print()


# ── Command class ─────────────────────────────────────────────────────────────

class NixOSCommand(Command):
    """NixOS integration command handlers"""

    def __init__(self):
        super().__init__()

    def generate(self, args) -> int:
        """Generate NixOS modules from a project"""
        try:
            from nixos_generator import NixOSGenerator

            project_slug = args.slug

            # Always resolve the project first: it is referenced later regardless
            # of whether an explicit output dir was given via -o/--output.
            project = self.get_project_or_exit(project_slug)

            # Auto-detect output directory for nixos-config projects
            if args.output:
                output_dir = Path(args.output)
                output_dir.mkdir(parents=True, exist_ok=True)
            else:
                # Check if this is a nixos-config project
                if project['project_type'] == 'nixos-config' and project['repo_url']:
                    config_path = Path(project['repo_url'])
                    modules_dir = config_path / 'modules'
                    modules_dir.mkdir(parents=True, exist_ok=True)
                    output_dir = modules_dir
                    print(f"\n🔧 Generating NixOS configuration for {project_slug}...")
                    print(f"   Auto-detected nixos-config project")
                    print(f"   Output: {output_dir}\n")
                else:
                    output_dir = Path('/tmp/nixos-gen')
                    output_dir.mkdir(parents=True, exist_ok=True)
                    print(f"\n🔧 Generating NixOS configuration for {project_slug}...")
                    print(f"   Output: {output_dir}\n")

            # Monkey-patch NixOSGenerator to inject TempleDB header
            _orig_nix = NixOSGenerator.generate_nix_module
            _orig_hm = NixOSGenerator.generate_home_manager_module

            def _nix_with_header(self_gen, config):
                return _with_header(_orig_nix(self_gen, config), project_slug)

            def _hm_with_header(self_gen, config):
                return _with_header(_orig_hm(self_gen, config), project_slug)

            NixOSGenerator.generate_nix_module = _nix_with_header
            NixOSGenerator.generate_home_manager_module = _hm_with_header

            try:
                with NixOSGenerator() as gen:
                    config = gen.generate_config(
                        project_slug,
                        cathedral_path=args.cathedral_path,
                        include_home_manager=not args.no_home_manager,
                        include_templedb=args.include_templedb
                    )

                    nixos_path = output_dir / f"{project_slug}-nixos.nix"
                    nixos_module = gen.generate_nix_module(config)
                    nixos_path.write_text(nixos_module)
                    print(f"✓ NixOS module: {nixos_path}")

                    if not args.no_home_manager:
                        hm_path = output_dir / f"{project_slug}-home.nix"
                        hm_module = gen.generate_home_manager_module(config)
                        hm_path.write_text(hm_module)
                        print(f"✓ Home Manager module: {hm_path}")

                    print(f"\n📊 Configuration Summary:")
                    print(f"   System packages: {len(config.system_packages)}")
                    print(f"   Home packages: {len(config.home_packages)}")
                    print(f"   Environment vars: {len(config.environment_vars)}")
                    print(f"   Secrets: {len(config.secrets)}")

                    print(f"\n💡 Next steps:")
                    print(f"   1. Review generated modules in {output_dir}")
                    print(f"   2. Copy to /etc/nixos/")
                    print(f"   3. Import in your flake.nix")
                    print(f"   4. Run: sudo nixos-rebuild test")
            finally:
                NixOSGenerator.generate_nix_module = _orig_nix
                NixOSGenerator.generate_home_manager_module = _orig_hm

            _mark_clean()
            return 0

        except Exception as e:
            logger.error(f"Failed to generate NixOS config: {e}", exc_info=True)
            return 1

    def export(self, args) -> int:
        """Export Cathedral package with NixOS modules"""
        try:
            from nixos_generator import NixOSGenerator

            project_slug = args.slug
            output_dir = Path(args.output) if args.output else Path('/tmp/nixos-gen')

            print(f"\n📦 Exporting {project_slug} with NixOS integration...")
            print(f"   Output: {output_dir}\n")

            with NixOSGenerator() as gen:
                nixos_path, hm_path = gen.export_cathedral_with_nix(project_slug, output_dir)

                print(f"\n✅ Export complete!")
                print(f"\n📁 Generated files:")
                print(f"   - Cathedral package: {project_slug}.cathedral.tar.zst")
                print(f"   - NixOS module: {nixos_path.name}")
                print(f"   - Home Manager module: {hm_path.name}")
                print(f"   - Integration guide: {project_slug}-INTEGRATION.md")
                print(f"\n💡 Read the integration guide:")
                print(f"   cat {output_dir}/{project_slug}-INTEGRATION.md")

            return 0

        except Exception as e:
            logger.error(f"Failed to export: {e}", exc_info=True)
            return 1

    def detect(self, args) -> int:
        """Detect dependencies and show what would be generated"""
        try:
            from nixos_generator import NixOSGenerator

            project_slug = args.slug
            print(f"\n🔍 Analyzing {project_slug}...\n")

            with NixOSGenerator() as gen:
                file_types = gen.get_project_file_types(project_slug)
                print(f"📊 File Type Distribution:")
                for ftype, count in sorted(file_types.items(), key=lambda x: x[1], reverse=True)[:10]:
                    print(f"   {ftype}: {count} files")

                packages = gen.detect_system_packages(file_types)
                print(f"\n📦 Detected Packages ({len(packages)}):")
                for pkg in sorted(packages):
                    print(f"   - {pkg}")

                env_vars = gen.get_project_env_vars(project_slug)
                print(f"\n🔐 Environment Variables ({len(env_vars)}):")
                for key, value in list(env_vars.items())[:5]:
                    display_value = value[:40] + '...' if len(value) > 40 else value
                    print(f"   {key} = {display_value}")
                if len(env_vars) > 5:
                    print(f"   ... and {len(env_vars) - 5} more")

                secrets = gen.get_project_secrets(project_slug)
                print(f"\n🔑 Secrets ({len(secrets)}):")
                for secret in secrets[:5]:
                    print(f"   - {secret['key_name']} ({secret.get('profile', 'default')})")
                if len(secrets) > 5:
                    print(f"   ... and {len(secrets) - 5} more")

                print(f"\n💡 To generate NixOS modules:")
                print(f"   ./templedb nixos generate {project_slug}")

            return 0

        except Exception as e:
            logger.error(f"Failed to detect dependencies: {e}", exc_info=True)
            return 1

    def system_test(self, args) -> int:
        """Test system configuration (nixos-rebuild test)"""
        try:
            from services.system_service import SystemService
            service = SystemService()
            print(f"🧪 Testing system configuration: {args.slug}")
            result = service.test_system(args.slug, dry_run=args.dry_run)
            if result['success']:
                print("\n✅ Test successful!")
            else:
                print(f"\n❌ Test failed (exit code {result['exit_code']})")
            if result.get('stdout'):
                print("\n📋 Output:")
                print(result['stdout'])
            if result.get('stderr'):
                print("\n⚠️  Errors/Warnings:")
                print(result['stderr'])
            return 0 if result['success'] else 1
        except Exception as e:
            logger.error(f"Failed to test system: {e}", exc_info=True)
            return 1

    def update_input(self, args) -> int:
        """Update a flake input"""
        try:
            from services.system_service import SystemService
            service = SystemService()
            print(f"🔄 Updating flake input '{args.input}' for {args.slug}...")
            result = service.update_flake_input(args.slug, args.input)
            if result['success']:
                print(f"✅ Updated {args.input}")
            else:
                print(f"❌ Failed to update {args.input}")
            if result.get('stdout'):
                print(result['stdout'])
            if result.get('stderr'):
                print(result['stderr'])
            return 0 if result['success'] else 1
        except Exception as e:
            logger.error(f"Failed to update input: {e}", exc_info=True)
            return 1

    def rebuild(self, args) -> int:
        """Rebuild NixOS system"""
        # Check for pending migrations before rebuilding
        try:
            from migrator import Migrator
            from db_utils import DB_PATH
            m = Migrator(DB_PATH)
            pending = sum(1 for s in m.status() if not s["applied"])
            if pending > 0:
                print(f"⚠ {pending} pending database migration(s)")
                print(f"  Run: templedb db migrate\n")
        except Exception:
            pass

        if not _check_dirty_and_prompt():
            return 1

        if hasattr(args, 'update_input') and args.update_input:
            print(f"🔄 Updating flake input: {args.update_input}")
            import argparse
            update_args = argparse.Namespace(slug=args.slug, input=args.update_input)
            result = self.update_input(update_args)
            if result != 0:
                print("❌ Failed to update input, aborting rebuild")
                return result
            print()

        return self.system_switch(args)

    def system_switch(self, args) -> int:
        """Switch to system configuration (nixos-rebuild switch)"""
        if not _check_dirty_and_prompt():
            return 1

        try:
            from services.system_service import SystemService

            verbose = getattr(args, 'verbose', False)
            show_trace = getattr(args, 'show_trace', False)
            no_update_lock = getattr(args, 'no_update_lock_file', False)
            yes = getattr(args, 'yes', False)

            service = SystemService()
            print(f"🚀 Switching to system configuration: {args.slug}")

            if args.with_home_manager:
                print("   Including home-manager rebuild")

            if args.dry_run:
                print("⚠️  DRY RUN MODE - No changes will be made")
            else:
                print("⚠️  This will activate the configuration permanently!")
                print("   Consider running 'nixos system-test' first.")
                if yes:
                    response = 'yes'
                else:
                    response = input("\nContinue? (yes/no): ")
                if response.lower() != 'yes':
                    print("Cancelled")
                    return 0

            result = service.switch_system(
                args.slug,
                dry_run=args.dry_run,
                with_home_manager=args.with_home_manager,
                verbose=verbose,
                show_trace=show_trace,
                no_update_lock_file=no_update_lock,
            )

            if result['success']:
                print("\n✅ Switch successful!")
                if result.get('nixos_generation'):
                    print(f"   NixOS generation: {result['nixos_generation']}")
                if result.get('home_manager'):
                    hm = result['home_manager']
                    if hm['success']:
                        print(f"   home-manager generation: {hm.get('generation', 'N/A')}")
                    else:
                        print(f"   ⚠️  home-manager rebuild failed")
                        if hm.get('error'):
                            print(f"      Error: {hm['error']}")
                print("\n✨ System configuration is now active and will persist across reboots.")
            else:
                print(f"\n❌ Switch failed (exit code {result['exit_code']})")

            if result.get('stdout'):
                print("\n📋 Output:")
                print(result['stdout'])
            if result.get('stderr'):
                print("\n⚠️  Errors/Warnings:")
                print(result['stderr'])

            return 0 if result['success'] else 1

        except Exception as e:
            logger.error(f"Failed to switch system: {e}", exc_info=True)
            return 1

    def system_status(self, args) -> int:
        """Show current system deployment status"""
        try:
            from services.system_service import SystemService
            service = SystemService()
            status = service.get_system_status()
            print(f"\n🖥️  System Status")
            print(f"   Current generation: {status.get('current_generation', 'unknown')}")
            print(f"   Last switch: {status.get('last_switch', 'unknown')}")
            print(f"   NixOS version: {status.get('nixos_version', 'unknown')}")
            return 0
        except Exception as e:
            logger.error(f"Failed to get system status: {e}", exc_info=True)
            return 1

    def system_history(self, args) -> int:
        """Show deployment history"""
        try:
            conn = _get_conn()
            limit = getattr(args, 'limit', 10)
            project_filter = getattr(args, 'project', None)
            query = "SELECT * FROM system_deployments"
            params = []
            if project_filter:
                query += " WHERE project_id = (SELECT id FROM projects WHERE slug = ?)"
                params.append(project_filter)
            query += " ORDER BY deployed_at DESC LIMIT ?"
            params.append(limit)
            rows = conn.execute(query, params).fetchall()
            if not rows:
                print("No deployment history found.")
                return 0
            for row in rows:
                print(f"  [{row[0]}] {row[-1]} — exit {row[-2]}")
            return 0
        except Exception as e:
            logger.error(f"Failed to get history: {e}", exc_info=True)
            return 1

    def system_rollback(self, args) -> int:
        """Rollback to previous deployment"""
        try:
            from services.system_service import SystemService
            service = SystemService()
            deployment_id = getattr(args, 'deployment_id', None)
            print(f"⏪ Rolling back{'to deployment ' + str(deployment_id) if deployment_id else ' to previous'}...")
            result = service.rollback_system(deployment_id)
            if result['success']:
                print("✅ Rollback successful!")
            else:
                print(f"❌ Rollback failed")
            return 0 if result['success'] else 1
        except Exception as e:
            logger.error(f"Failed to rollback: {e}", exc_info=True)
            return 1

    def set_type(self, args) -> int:
        """Set project type"""
        try:
            from db_utils import execute
            execute("UPDATE projects SET project_type = ? WHERE slug = ?", (args.type, args.slug))
            print(f"✓ Set {args.slug} type to {args.type}")
            return 0
        except Exception as e:
            logger.error(f"Failed to set type: {e}", exc_info=True)
            return 1

    def list_configs(self, args) -> int:
        """List all nixos-config projects"""
        conn = _get_conn()
        rows = conn.execute(
            "SELECT slug, name, repo_url FROM projects WHERE project_type = 'nixos-config'"
        ).fetchall()
        if not rows:
            print("No nixos-config projects found.")
            return 0
        for row in rows:
            print(f"  {row[0]}  {row[1] or ''}  {row[2] or ''}")
        return 0

    def config_get(self, args) -> int:
        """Get system configuration value"""
        conn = _get_conn()
        row = conn.execute("SELECT value FROM system_config WHERE key = ?", (args.key,)).fetchone()
        if row:
            print(row[0])
        else:
            print(f"Key not found: {args.key}", file=sys.stderr)
            return 1
        return 0

    def config_set(self, args) -> int:
        """Set system configuration value"""
        try:
            from db_utils import execute
            now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
            execute(
                "INSERT INTO system_config (key, value, updated_at) VALUES (?, ?, ?) "
                "ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at",
                (args.key, args.value, now),
            )
            print(f"✓ Set {args.key} = {args.value}")
            return 0
        except Exception as e:
            logger.error(f"Failed to set config: {e}", exc_info=True)
            return 1

    def config_list(self, args) -> int:
        """List all system configuration"""
        conn = _get_conn()
        rows = conn.execute(
            "SELECT key, value FROM system_config ORDER BY key"
        ).fetchall()
        if not rows:
            print("No system config found.")
            return 0
        key_w = max(len(r[0]) for r in rows)
        for row in rows:
            print(f"  {row[0]:{key_w}}  {row[1]}")
        return 0

    def add_package(self, args) -> int:
        """Add CLI tool to managed packages"""
        try:
            from db_utils import execute
            now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
            execute(
                "INSERT INTO nixos_packages (project_slug, name, scope, flake_uri, version, created_at) "
                "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING",
                (args.slug, args.name or args.slug, args.scope,
                 args.flake_uri, args.version, now),
            )
            print(f"✓ Added package {args.name or args.slug}")
            return 0
        except Exception as e:
            logger.error(f"Failed to add package: {e}", exc_info=True)
            return 1

    def remove_package(self, args) -> int:
        """Remove CLI tool from managed packages"""
        try:
            from db_utils import execute
            execute("DELETE FROM nixos_packages WHERE project_slug = ?", (args.slug,))
            print(f"✓ Removed package for {args.slug}")
            return 0
        except Exception as e:
            logger.error(f"Failed to remove package: {e}", exc_info=True)
            return 1

    def list_packages(self, args) -> int:
        """List all managed packages"""
        conn = _get_conn()
        scope = getattr(args, 'scope', None)
        if scope:
            rows = conn.execute(
                "SELECT project_slug, name, scope FROM nixos_packages WHERE scope = ? ORDER BY name",
                (scope,)
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT project_slug, name, scope FROM nixos_packages ORDER BY name"
            ).fetchall()
        if not rows:
            print("No packages found.")
            return 0
        for row in rows:
            print(f"  {row[1]}  ({row[2]})  [{row[0]}]")
        return 0

    def nixos_status(self, args) -> int:
        """Show full pipeline state"""
        slug = _resolve_slug(getattr(args, 'slug', None))
        if not slug:
            return 1
        _nixos_status(slug)
        return 0

    def nixos_edit_template(self, args) -> int:
        """Open .nix.template files in $EDITOR"""
        import os
        import subprocess as _sp

        editor = os.environ.get('VISUAL') or os.environ.get('EDITOR') or 'nano'
        slug = _resolve_slug(getattr(args, 'slug', None))
        if not slug:
            return 1

        conn = _get_conn()
        proj = conn.execute("SELECT repo_url FROM projects WHERE slug = ?", (slug,)).fetchone()
        if not proj or not proj[0]:
            print(f"Project '{slug}' has no repo_url set.", file=sys.stderr)
            return 1

        repo = Path(proj[0])
        templates = sorted(repo.rglob("*.nix.template"))
        if not templates:
            print(f"No .nix.template files found under {repo}", file=sys.stderr)
            return 1

        print(f"Opening {len(templates)} template(s) in {editor}:")
        for t in templates:
            print(f"  {t.relative_to(repo)}")

        _sp.run([editor] + [str(t) for t in templates])
        return 0

    def doctor(self, args) -> int:
        """Diagnose common NixOS-config activation problems (read-only).

        Checks the templedb CLI symlinks, the database, each nixos-config
        project's checkout/modules, generated modules for the unquoted
        dotted-key bug, and whether /etc/nixos actually imports them.
        """
        import os
        import re as _re
        from services.system_service import SystemService

        problems = 0
        warnings = 0

        def ok(msg):
            print(f"  ✓ {msg}")

        def warn(msg):
            nonlocal warnings
            warnings += 1
            print(f"  ⚠ {msg}")

        def err(msg):
            nonlocal problems
            problems += 1
            print(f"  ✗ {msg}")

        print("\n\U0001f489 TempleDB NixOS doctor\n")

        # 1. CLI launcher symlinks (the templedb vs templeDB casing trap)
        print("CLI launchers:")
        home = Path.home()
        for name in ("templedb", "tdb"):
            link = home / ".local" / "bin" / name
            if not link.exists() and not link.is_symlink():
                warn(f"~/.local/bin/{name} not installed")
            elif link.is_symlink() and not link.resolve().exists():
                err(f"~/.local/bin/{name} is a dangling symlink -> {os.readlink(link)}")
            else:
                ok(f"~/.local/bin/{name} -> {link.resolve()}")

        # 2. Database
        print("\nDatabase:")
        db_path = Path(getattr(self, 'db_path', '') or
                       os.environ.get('DB_PATH', '') or
                       (home / ".local/share/templedb/templedb.sqlite"))
        if db_path.exists():
            ok(f"{db_path} ({db_path.stat().st_size // (1024*1024)} MB)")
        else:
            err(f"database not found at {db_path}")

        # 2b. Migration status
        print("\nMigrations:")
        try:
            from migrator import Migrator
            m = Migrator(str(db_path))
            status = m.status()
            pending = sum(1 for s in status if not s["applied"])
            applied = sum(1 for s in status if s["applied"])
            if pending == 0:
                ok(f"all {applied} migrations applied")
            else:
                warn(f"{pending} pending migration(s) — run: templedb db migrate")
        except Exception as e:
            warn(f"could not check migrations: {e}")

        # 3. nixos-config projects
        service = SystemService()
        projects = service.get_nixos_config_projects()
        if args.slug:
            projects = [p for p in projects if p['slug'] == args.slug]
            if not projects:
                err(f"no nixos-config project named '{args.slug}'")
                return 1
        if not projects:
            warn("no nixos-config projects (templedb nixos set-type <slug> nixos-config)")

        # What `nixos generate` writes for a nixos-config project today:
        generated_names = {"templedb-managed-system.nix", "templedb-managed.nix"}
        # Read /etc/nixos config text once for drift detection.
        etc_text = ""
        for f in (Path("/etc/nixos/configuration.nix"), Path("/etc/nixos/flake.nix")):
            try:
                etc_text += f.read_text()
            except OSError:
                pass

        # A dotted attr key like `git_server.url = ...`. Only a problem *inside*
        # a string-valued attrset (environment.variables / home.sessionVariables),
        # where Nix would read the dot as a nested attrset and break the type.
        dotted_key = _re.compile(r"^\s*([A-Za-z_][\w'-]*(?:\.[A-Za-z_][\w'-]*)+)\s*=")
        env_block = _re.compile(r"\b(?:environment\.variables|home\.sessionVariables)\s*=\s*\{")

        def find_bad_env_keys(text):
            bad, depth, in_env = [], 0, False
            for line in text.splitlines():
                if not in_env:
                    if env_block.search(line):
                        in_env = True
                        depth = line.count("{") - line.count("}")
                    continue
                m = dotted_key.match(line)
                if m:
                    bad.append(m.group(1))
                depth += line.count("{") - line.count("}")
                if depth <= 0:
                    in_env = False
            return bad

        for proj in projects:
            slug = proj['slug']
            print(f"\nProject '{slug}':")
            repo = proj.get('repo_url')
            if not repo:
                err("no repo_url set (templedb has nowhere to write modules)")
                continue
            checkout = Path(repo)
            if not checkout.exists():
                err(f"checkout missing: {checkout}")
                continue
            ok(f"checkout: {checkout}")

            modules_dir = checkout / "modules"
            module_files = sorted(modules_dir.glob("*.nix")) if modules_dir.exists() else []
            if not module_files:
                warn(f"no generated modules in {modules_dir} (run: templedb nixos generate {slug})")
            for mf in module_files:
                text = mf.read_text()
                # Unquoted dotted attr keys -> Nix reads them as nested attrsets,
                # which breaks environment.variables / home.sessionVariables.
                bad = find_bad_env_keys(text)
                if bad:
                    err(f"{mf.name}: unquoted dotted key(s) {bad} - will fail eval; "
                        f"regenerate with a fixed templedb or quote them")
                else:
                    ok(f"{mf.name}: no unquoted dotted keys")

                # Drift: is this file actually imported by /etc/nixos?
                if etc_text and mf.name in etc_text:
                    ok(f"{mf.name}: imported by /etc/nixos")
                elif etc_text:
                    warn(f"{mf.name}: not referenced in /etc/nixos (won't take effect)")

            # Naming drift between what's deployed and what generate produces now.
            deployed = {mf.name for mf in module_files}
            if deployed and not (deployed & generated_names) and \
                    any(n in etc_text for n in deployed):
                warn(f"deployed module names {sorted(deployed)} differ from what "
                     f"`nixos generate` now writes {sorted(generated_names)} - "
                     f"regeneration will not overwrite the imported files")

        # Summary
        print(f"\n─────\nSummary: {problems} error(s), {warnings} warning(s)")
        if problems == 0 and warnings == 0:
            print("All checks passed ✨")
        return 1 if problems else 0


    # ── Dotfiles ──────────────────────────────────────────────────────────────

    def dotfiles_apply(self, args) -> int:
        """Apply dotfile symlinks from the system_config dotfiles manifest."""
        conn = _get_conn()
        manifest = self._get_dotfiles_manifest(conn)

        if not manifest:
            print("No dotfiles configured.")
            print("Add entries with: templedb nixos dotfiles-add <project> <source> <target>")
            return 0

        from repositories import ConfigLinkRepository
        config_repo = ConfigLinkRepository()

        created = 0
        skipped = 0
        already_ok = 0

        for entry in manifest:
            project_slug = entry['project']
            source_rel = entry['source']
            target_path = Path(entry['target']).expanduser()

            checkout_dir = Path.home() / '.config' / 'templedb' / 'checkouts' / project_slug
            source_abs = checkout_dir / source_rel

            if not source_abs.exists():
                print(f"  SKIP {source_rel} (source missing: {source_abs})")
                skipped += 1
                continue

            if target_path.is_symlink() and target_path.resolve() == source_abs.resolve():
                if args.verbose:
                    print(f"  OK   {target_path} -> {source_abs}")
                already_ok += 1
                continue

            # Back up existing file if not a symlink
            backup_path = None
            if target_path.exists() and not target_path.is_symlink():
                if not args.force:
                    print(f"  SKIP {target_path} (exists, use --force to replace)")
                    skipped += 1
                    continue
                backup_path = str(target_path) + '.templedb-backup'
                import shutil
                shutil.move(str(target_path), backup_path)
                print(f"  BACKUP {target_path} -> {backup_path}")
            elif target_path.is_symlink():
                target_path.unlink()

            # Create parent dirs and symlink
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.symlink_to(source_abs)
            print(f"  LINK {target_path} -> {source_abs}")
            created += 1

        print(f"\nDotfiles: {created} created, {already_ok} already OK, {skipped} skipped")
        return 0

    def dotfiles_add(self, args) -> int:
        """Add a dotfile mapping to the manifest."""
        conn = _get_conn()
        manifest = self._get_dotfiles_manifest(conn)

        # Check for duplicate
        for entry in manifest:
            if entry['project'] == args.project and entry['source'] == args.source:
                print(f"Already mapped: {args.source} -> {entry['target']}")
                return 0

        manifest.append({
            'project': args.project,
            'source': args.source,
            'target': args.target,
        })

        self._set_dotfiles_manifest(conn, manifest)
        conn.commit()
        print(f"Added: {args.project}:{args.source} -> {args.target}")
        return 0

    def dotfiles_remove(self, args) -> int:
        """Remove a dotfile mapping from the manifest."""
        conn = _get_conn()
        manifest = self._get_dotfiles_manifest(conn)

        new_manifest = [
            e for e in manifest
            if not (e['project'] == args.project and e['source'] == args.source)
        ]

        if len(new_manifest) == len(manifest):
            print(f"No mapping found for {args.project}:{args.source}")
            return 1

        self._set_dotfiles_manifest(conn, new_manifest)
        conn.commit()
        print(f"Removed: {args.project}:{args.source}")
        return 0

    def dotfiles_list(self, args) -> int:
        """List all dotfile mappings."""
        conn = _get_conn()
        manifest = self._get_dotfiles_manifest(conn)

        if not manifest:
            print("No dotfiles configured.")
            return 0

        checkout_base = Path.home() / '.config' / 'templedb' / 'checkouts'

        for entry in manifest:
            source_abs = checkout_base / entry['project'] / entry['source']
            target = Path(entry['target']).expanduser()

            if target.is_symlink() and target.resolve() == source_abs.resolve():
                status = "OK"
            elif target.exists():
                status = "CONFLICT"
            elif not source_abs.exists():
                status = "NO SOURCE"
            else:
                status = "NOT LINKED"

            print(f"  [{status:>10}] {entry['project']}:{entry['source']} -> {entry['target']}")

        return 0

    def _get_dotfiles_manifest(self, conn) -> list:
        row = conn.execute(
            "SELECT value FROM system_config WHERE key = 'nixos.dotfiles'"
        ).fetchone()
        if row:
            return json.loads(row[0])
        return []

    def _set_dotfiles_manifest(self, conn, manifest: list):
        conn.execute(
            "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
            "VALUES ('nixos.dotfiles', ?, datetime('now'))",
            (json.dumps(manifest),)
        )

    # ── Host Management ────────────────────────────────────────────────

    def host_list(self, args) -> int:
        """List all registered NixOS hosts."""
        conn = _get_conn()
        rows = conn.execute(
            "SELECT key, value FROM system_config WHERE key LIKE 'nixos.host.%' ORDER BY key"
        ).fetchall()

        if not rows:
            print("No hosts registered.")
            print("  Import with: templedb nixos host import <hostname>")
            return 0

        current = conn.execute(
            "SELECT value FROM system_config WHERE key = 'nixos.flake_output'"
        ).fetchone()
        active_host = current[0] if current else None

        print(f"\nNixOS Hosts ({len(rows)}):\n")
        for r in rows:
            hostname = r[0].replace("nixos.host.", "")
            active = " (active)" if hostname == active_host else ""
            host_file = r[1]

            # Count host-scoped config keys
            count = conn.execute(
                "SELECT COUNT(*) FROM system_config WHERE key LIKE ?",
                (f"{hostname}.%",)
            ).fetchone()[0]

            print(f"  {hostname:30s} {host_file:40s} {count} overrides{active}")

        return 0

    def host_show(self, args) -> int:
        """Show host-specific configuration."""
        conn = _get_conn()
        hostname = args.hostname

        # Get host-scoped overrides
        overrides = conn.execute(
            "SELECT key, value FROM system_config WHERE key LIKE ? ORDER BY key",
            (f"{hostname}.%",)
        ).fetchall()

        # Get host file
        host_file = conn.execute(
            "SELECT value FROM system_config WHERE key = ?",
            (f"nixos.host.{hostname}",)
        ).fetchone()

        print(f"\nHost: {hostname}")
        if host_file:
            print(f"  Config file: {host_file[0]}")

        if overrides:
            print(f"\n  Host-scoped overrides ({len(overrides)}):")
            for r in overrides:
                key = r[0][len(hostname) + 1:]  # strip hostname prefix
                print(f"    {key:40s} {r[1][:60]}")
        else:
            print(f"\n  No host-scoped overrides.")
            print(f"  Set with: templedb nixos host set {hostname} <key> <value>")

        # Show what this host would inherit (non-host-scoped keys)
        defaults = conn.execute(
            "SELECT key, value FROM system_config "
            "WHERE key LIKE 'nixos.let.%' ORDER BY key"
        ).fetchall()
        if defaults:
            print(f"\n  Inherited defaults (from system-wide config):")
            for r in defaults:
                print(f"    {r[0]:40s} {r[1][:60]}")

        return 0

    def host_set(self, args) -> int:
        """Set a host-scoped config override."""
        conn = _get_conn()
        hostname = args.hostname
        key = f"{hostname}.{args.key}"
        value = args.value

        conn.execute(
            "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
            "VALUES (?, ?, datetime('now'))", (key, value)
        )
        conn.commit()
        print(f"Set {key} = {value}")
        return 0

    def host_import(self, args) -> int:
        """Import host-specific values from an existing host .nix file."""
        import re as _re

        conn = _get_conn()
        hostname = args.hostname

        slug = _resolve_slug(getattr(args, 'slug', None))
        if not slug:
            return 1

        proj = conn.execute("SELECT repo_url FROM projects WHERE slug = ?", (slug,)).fetchone()
        if not proj or not proj[0]:
            print(f"Project '{slug}' has no repo_url set.", file=sys.stderr)
            return 1

        repo = Path(proj[0])

        # Find host file
        host_file = repo / "hosts" / f"{hostname}.nix"
        if not host_file.exists():
            print(f"Host file not found: {host_file}")
            print(f"  Available: {', '.join(f.stem for f in (repo / 'hosts').glob('*.nix'))}")
            return 1

        content = host_file.read_text()
        imported = 0

        # Extract key values
        # hostname
        m = _re.search(r'hostName\s*=\s*"([^"]+)"', content)
        if m:
            conn.execute(
                "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
                "VALUES (?, ?, datetime('now'))",
                (f"{hostname}.networking.hostName", m.group(1))
            )
            print(f"  {hostname}.networking.hostName = {m.group(1)}")
            imported += 1

        # Video drivers
        m = _re.search(r'videoDrivers\s*=\s*\[\s*"([^"]+)"', content)
        if m:
            conn.execute(
                "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
                "VALUES (?, ?, datetime('now'))",
                (f"{hostname}.videoDriver", m.group(1))
            )
            print(f"  {hostname}.videoDriver = {m.group(1)}")
            imported += 1

        # Boot loader type
        if "systemd-boot.enable = true" in content:
            boot_type = "systemd-boot"
        elif "grub.enable = true" in content:
            boot_type = "grub"
        else:
            boot_type = "unknown"
        conn.execute(
            "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
            "VALUES (?, ?, datetime('now'))",
            (f"{hostname}.bootLoader", boot_type)
        )
        print(f"  {hostname}.bootLoader = {boot_type}")
        imported += 1

        # GRUB device
        m = _re.search(r'grub\.device\s*=\s*"([^"]+)"', content)
        if m:
            conn.execute(
                "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
                "VALUES (?, ?, datetime('now'))",
                (f"{hostname}.grubDevice", m.group(1))
            )
            print(f"  {hostname}.grubDevice = {m.group(1)}")
            imported += 1

        # Location
        m = _re.search(r'location\.latitude\s*=\s*([0-9.]+)', content)
        if m:
            conn.execute(
                "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
                "VALUES (?, ?, datetime('now'))",
                (f"{hostname}.location.latitude", m.group(1))
            )
            print(f"  {hostname}.location.latitude = {m.group(1)}")
            imported += 1

        m = _re.search(r'location\.longitude\s*=\s*(-?[0-9.]+)', content)
        if m:
            conn.execute(
                "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
                "VALUES (?, ?, datetime('now'))",
                (f"{hostname}.location.longitude", m.group(1))
            )
            print(f"  {hostname}.location.longitude = {m.group(1)}")
            imported += 1

        # Register the host file
        conn.execute(
            "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
            "VALUES (?, ?, datetime('now'))",
            (f"nixos.host.{hostname}", f"hosts/{hostname}.nix")
        )

        conn.commit()
        print(f"\nImported {imported} host-specific values for {hostname}")
        return 0

    def host_activate(self, args) -> int:
        """Set which host this machine is (sets nixos.flake_output)."""
        conn = _get_conn()
        hostname = args.hostname

        # Verify host exists
        host = conn.execute(
            "SELECT value FROM system_config WHERE key = ?",
            (f"nixos.host.{hostname}",)
        ).fetchone()
        if not host:
            print(f"Host '{hostname}' not registered.")
            print(f"  Available hosts: templedb nixos host list")
            return 1

        conn.execute(
            "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
            "VALUES ('nixos.flake_output', ?, datetime('now'))", (hostname,)
        )
        conn.commit()
        print(f"Activated host: {hostname}")
        print(f"  Rebuild with: templedb nixos rebuild system_config")
        return 0

    def host_clone(self, args) -> int:
        """Clone an existing host config to a new hostname."""
        conn = _get_conn()
        source = args.source
        target = args.target

        # Verify source exists
        source_keys = conn.execute(
            "SELECT key, value FROM system_config WHERE key LIKE ?",
            (f"{source}.%",)
        ).fetchall()

        if not source_keys:
            print(f"Source host '{source}' has no config keys.")
            print(f"  Import first: templedb nixos host import {source}")
            return 1

        # Check source host registration
        source_host = conn.execute(
            "SELECT value FROM system_config WHERE key = ?",
            (f"nixos.host.{source}",)
        ).fetchone()

        # Clone all host-scoped keys
        cloned = 0
        for row in source_keys:
            old_key = row[0]
            new_key = old_key.replace(f"{source}.", f"{target}.", 1)
            new_value = row[1]

            # Update hostname references in values
            if source in str(new_value):
                new_value = new_value.replace(source, target)

            conn.execute(
                "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
                "VALUES (?, ?, datetime('now'))", (new_key, new_value)
            )
            cloned += 1

        # Register the new host
        conn.execute(
            "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
            "VALUES (?, ?, datetime('now'))",
            (f"nixos.host.{target}", f"hosts/{target}.nix")
        )

        conn.commit()

        print(f"Cloned {source} → {target} ({cloned} keys)")
        print(f"\n  Host-specific overrides for {target}:")
        new_keys = conn.execute(
            "SELECT key, value FROM system_config WHERE key LIKE ? ORDER BY key",
            (f"{target}.%",)
        ).fetchall()
        for r in new_keys:
            k = r[0][len(target) + 1:]
            print(f"    {k:40s} {r[1][:60]}")

        print(f"\n  Customize: templedb nixos host set {target} <key> <value>")
        print(f"  Activate:  templedb nixos host activate {target}")
        print(f"  Generate:  templedb nixos generate-all --host {target}")
        return 0

    # ── Import / Generate-All ────────────────────────────────────────────

    def import_config(self, args) -> int:
        """Comprehensively import NixOS config into system_config table."""
        import re as _re

        slug = _resolve_slug(getattr(args, 'slug', None))
        if not slug:
            return 1

        conn = _get_conn()
        proj = conn.execute("SELECT repo_url FROM projects WHERE slug = ?", (slug,)).fetchone()
        if not proj or not proj[0]:
            print(f"Project '{slug}' has no repo_url set.", file=sys.stderr)
            return 1

        repo = Path(proj[0])
        imported = 0

        def _set(key, value):
            nonlocal imported
            conn.execute(
                "INSERT OR REPLACE INTO system_config (key, value, updated_at) "
                "VALUES (?, ?, datetime('now'))", (key, value)
            )
            imported += 1

        # ── home.nix ──────────────────────────────────────────────────────
        home_path = repo / 'home.nix'
        if home_path.exists():
            content = home_path.read_text()
            print("home.nix:")

            # Portable path let-bindings
            let_section = _re.search(
                r'# === Portable path definitions ===\n(.*?)(?=\n\n|\n  \w+\s*=\s*pkgs\.)',
                content, _re.DOTALL
            )
            if let_section:
                for m in _re.finditer(r'^\s+(\w+)\s*=\s*"(/[^"]*)";\s*$', let_section.group(1), _re.MULTILINE):
                    _set(f"nixos.let.home.{m.group(1)}", m.group(2))
                    print(f"  nixos.let.home.{m.group(1)} = {m.group(2)}")

            # Packages — extract from home.packages = with pkgs; [ ... ];
            pkg_block = _re.search(r'home\.packages\s*=\s*with pkgs;\s*\[(.*?)\];', content, _re.DOTALL)
            if pkg_block:
                current_category = "uncategorized"
                for line in pkg_block.group(1).split('\n'):
                    line = line.strip()
                    if line.startswith('#') and not line.startswith('# Custom'):
                        current_category = line.lstrip('# ').strip().lower().replace(' ', '_')
                        continue
                    # Skip flake-input packages and local packages
                    if not line or line.startswith('#') or '.' in line or line.startswith('my') or line == 'voiceAIPackage' or line == 'ghcNPackages':
                        continue
                    pkg = line.rstrip(';').strip()
                    if pkg and _re.match(r'^[a-zA-Z][\w-]*$', pkg):
                        _set(f"nixos.pkg.user.{current_category}.{pkg}", "true")
                print(f"  Packages: {sum(1 for k in [] if True)} (see nixos.pkg.user.*)")

            # Shell aliases
            alias_block = _re.search(r'shellAliases\s*=\s*\{(.*?)\};', content, _re.DOTALL)
            if alias_block:
                for m in _re.finditer(r'(\w+)\s*=\s*"([^"]*)"', alias_block.group(1)):
                    _set(f"nixos.alias.{m.group(1)}", m.group(2))
                print(f"  Aliases: imported")

            # Programs enabled
            for m in _re.finditer(r'programs\.(\w+)\s*=\s*\{\s*\n\s*enable\s*=\s*true', content):
                _set(f"nixos.program.{m.group(1)}", "true")
                print(f"  nixos.program.{m.group(1)} = true")

            # home.username and homeDirectory
            m = _re.search(r'home\.username\s*=\s*"([^"]+)"', content)
            if m:
                _set("nixos.username", m.group(1))
            m = _re.search(r'home\.homeDirectory\s*=\s*(\w+)', content)
            if m and m.group(1) != 'homeDir':  # skip if it's a variable reference
                _set("nixos.home_directory", m.group(1))

            # home.stateVersion
            m = _re.search(r'home\.stateVersion\s*=\s*"([^"]+)"', content)
            if m:
                _set("nixos.home.stateVersion", m.group(1))

            # home.file entries
            for m in _re.finditer(r'"([^"]+)"\s*=\s*\{[^}]*source\s*=\s*\./([^;]+)', content):
                _set(f"nixos.home.file.{m.group(1)}", m.group(2).strip())
                print(f"  nixos.home.file.{m.group(1)} = {m.group(2).strip()}")

            # systemd user services
            for m in _re.finditer(r'systemd\.user\.services\.(\w[\w-]*)\s*=', content):
                _set(f"nixos.service.user.{m.group(1)}", "true")
                print(f"  nixos.service.user.{m.group(1)} = true")

        # ── configuration.nix ─────────────────────────────────────────────
        conf_path = repo / 'configuration.nix'
        if conf_path.exists():
            content = conf_path.read_text()
            print("\nconfiguration.nix:")

            # Portable path let-bindings
            let_section = _re.search(
                r'# === Portable path definitions ===\n(.*?)(?=\n\n|\n  # Port)',
                content, _re.DOTALL
            )
            if let_section:
                for m in _re.finditer(r'^\s+(\w+)\s*=\s*"(/[^"]*)";\s*$', let_section.group(1), _re.MULTILINE):
                    _set(f"nixos.let.configuration.{m.group(1)}", m.group(2))
                    print(f"  nixos.let.configuration.{m.group(1)} = {m.group(2)}")

            # System packages
            sys_pkg_block = _re.search(r'environment\.systemPackages\s*=\s*with pkgs;\s*\[(.*?)\];', content, _re.DOTALL)
            if sys_pkg_block:
                for line in sys_pkg_block.group(1).split('\n'):
                    line = line.strip()
                    if line.startswith('#'):
                        continue
                    pkg = line.rstrip(';').strip()
                    if pkg and _re.match(r'^[a-zA-Z][\w-]*$', pkg):
                        _set(f"nixos.pkg.system.{pkg}", "true")
                print(f"  System packages: imported")

            # Services enabled
            for m in _re.finditer(r'services\.(\w[\w.]*?)\.enable\s*=\s*true', content):
                svc = m.group(1).replace('.', '_')
                _set(f"nixos.service.system.{svc}", "true")
                print(f"  nixos.service.system.{svc} = true")

            # Programs enabled
            for m in _re.finditer(r'programs\.(\w[\w.]*?)\.enable\s*=\s*true', content):
                _set(f"nixos.program.system.{m.group(1)}", "true")

            # system.stateVersion
            m = _re.search(r'system\.stateVersion\s*=\s*"([^"]+)"', content)
            if m:
                _set("nixos.system.stateVersion", m.group(1))
                print(f"  nixos.system.stateVersion = {m.group(1)}")

            # time.timeZone
            m = _re.search(r'time\.timeZone\s*=\s*"([^"]+)"', content)
            if m:
                _set("nixos.timeZone", m.group(1))
                print(f"  nixos.timeZone = {m.group(1)}")

            # Firewall TCP ports
            tcp_block = _re.search(r'firewall\.allowedTCPPorts\s*=\s*\[(.*?)\];', content, _re.DOTALL)
            if tcp_block:
                ports = []
                for line in tcp_block.group(1).split('\n'):
                    line = _re.sub(r'#.*', '', line).strip()
                    for p in _re.findall(r'\b(\d+)\b', line):
                        ports.append(p)
                _set("nixos.firewall.tcp", json.dumps(sorted(set(ports), key=int)))
                print(f"  Firewall TCP: {len(ports)} ports")

            # Networking hostname
            m = _re.search(r'networking\.hostName\s*=\s*"([^"]+)"', content)
            if m:
                _set("nixos.networking.hostName", m.group(1))

            # Hardware settings
            for m in _re.finditer(r'hardware\.(\w[\w.]*?)\s*=\s*(true|false)', content):
                _set(f"nixos.hardware.{m.group(1)}", m.group(2))

            # Virtualisation
            for m in _re.finditer(r'virtualisation\.(\w[\w.]*?)\.enable\s*=\s*(true|false)', content):
                _set(f"nixos.virtualisation.{m.group(1)}", m.group(2))

            # Nix settings
            m = _re.search(r'experimental-features\s*=\s*\[([^\]]+)\]', content)
            if m:
                features = [f.strip().strip('"') for f in m.group(1).split()]
                _set("nixos.nix.experimental-features", json.dumps(features))

            # Git daemon
            m = _re.search(r'gitDaemon\.port\s*=\s*(\d+)', content)
            if m:
                _set("nixos.gitDaemon.port", m.group(1))

        # ── flake.nix ─────────────────────────────────────────────────────
        flake_path = repo / 'flake.nix'
        if flake_path.exists():
            content = flake_path.read_text()
            print("\nflake.nix:")
            for m in _re.finditer(r'^\s+(\S+)\.url\s*=\s*"([^"]+)";\s*$', content, _re.MULTILINE):
                _set(f"nixos.flake.input.{m.group(1)}", m.group(2))
                print(f"  nixos.flake.input.{m.group(1)} = {m.group(2)}")

        # ── hosts/ ────────────────────────────────────────────────────────
        hosts_dir = repo / 'hosts'
        if hosts_dir.exists():
            print("\nhosts/:")
            for host_file in hosts_dir.glob('*.nix'):
                host_name = host_file.stem
                _set(f"nixos.host.{host_name}", str(host_file.relative_to(repo)))
                print(f"  nixos.host.{host_name} = {host_file.relative_to(repo)}")

        conn.commit()
        print(f"\nImported {imported} config values from {slug}")
        print(f"  View with: templedb nixos config-list")
        print(f"  Generate:  templedb nixos generate-all {slug}")
        return 0

    def generate_all(self, args) -> int:
        """Generate all NixOS config from DB: render templates + generate managed modules."""
        slug = _resolve_slug(getattr(args, 'slug', None))
        if not slug:
            return 1

        conn = _get_conn()
        proj = conn.execute("SELECT id, repo_url FROM projects WHERE slug = ?", (slug,)).fetchone()
        if not proj or not proj[1]:
            print(f"Project '{slug}' has no repo_url set.", file=sys.stderr)
            return 1

        repo = Path(proj[1])
        dry_run = getattr(args, 'dry_run', False)

        # Determine active host
        host = getattr(args, 'host', None)
        if not host:
            host_row = conn.execute(
                "SELECT value FROM system_config WHERE key = 'nixos.flake_output'"
            ).fetchone()
            host = host_row[0] if host_row else None

        print(f"Generating all NixOS config for {slug}")
        print(f"  Config dir: {repo}")
        if host:
            print(f"  Host: {host}")
        print()

        # Step 1: Update let-bindings in nix files from system_config
        # Host-scoped keys override system-wide keys
        nix_files = {'home': 'home.nix', 'configuration': 'configuration.nix'}
        let_updated = 0

        for prefix_name, nix_file in nix_files.items():
            fpath = repo / nix_file
            if not fpath.exists():
                continue

            content = fpath.read_text()
            db_prefix = f"nixos.let.{prefix_name}."

            # Get all let-binding values from DB (system-wide defaults)
            rows = conn.execute(
                "SELECT key, value FROM system_config WHERE key LIKE ?",
                (f"{db_prefix}%",)
            ).fetchall()

            # Build var map with host overrides
            var_map = {}
            for row in rows:
                var_name = row[0][len(db_prefix):]
                var_map[var_name] = row[1]

            # Apply host-scoped overrides (e.g., zStation.nixos.let.home.homeDir)
            if host:
                host_prefix = f"{host}.{db_prefix}"
                host_rows = conn.execute(
                    "SELECT key, value FROM system_config WHERE key LIKE ?",
                    (f"{host_prefix}%",)
                ).fetchall()
                for row in host_rows:
                    var_name = row[0][len(host_prefix):]
                    var_map[var_name] = row[1]

            if not var_map:
                continue

            for var_name, new_value in var_map.items():

                # Replace in content: varName = "old_value"; → varName = "new_value";
                import re as _re
                pattern = _re.compile(
                    rf'(\s+{_re.escape(var_name)}\s*=\s*)"[^"]*"(;\s*$)',
                    _re.MULTILINE
                )
                new_content = pattern.sub(rf'\1"{new_value}"\2', content)
                if new_content != content:
                    content = new_content
                    let_updated += 1

            if not dry_run:
                fpath.write_text(content)
                print(f"  Updated {nix_file} ({let_updated} bindings)")
            else:
                print(f"  [DRY RUN] Would update {nix_file} ({let_updated} bindings)")

        # Step 2: Generate nix code from DB (packages, aliases, services, firewall)
        try:
            from nix_codegen import update_home_nix, update_configuration_nix, update_flake_inputs

            home_path = repo / 'home.nix'
            conf_path = repo / 'configuration.nix'
            flake_path = repo / 'flake.nix'

            if flake_path.exists():
                if not dry_run:
                    n = update_flake_inputs(flake_path)
                    print(f"  Updated flake.nix ({n} input URLs)")
                else:
                    print(f"  [DRY RUN] Would update flake.nix input URLs")

            if home_path.exists():
                if not dry_run:
                    n = update_home_nix(home_path)
                    print(f"  Updated home.nix ({n} managed sections)")
                else:
                    print(f"  [DRY RUN] Would update home.nix managed sections")

            if conf_path.exists():
                if not dry_run:
                    n = update_configuration_nix(conf_path)
                    print(f"  Updated configuration.nix ({n} managed sections)")
                else:
                    print(f"  [DRY RUN] Would update configuration.nix managed sections")
        except Exception as e:
            print(f"  Nix codegen: {e}")

        # Step 3: Render .nix.template files (woofs config, etc.)
        try:
            from template_renderer import TemplateRenderer
            renderer = TemplateRenderer()
            machine_name = conn.execute(
                "SELECT value FROM system_config WHERE key = 'nixos.flake_output'"
            ).fetchone()
            machine = machine_name[0] if machine_name else None

            if not dry_run:
                count = renderer.render_project_templates(
                    slug, repo, machine_name=machine
                )
                print(f"  Rendered {count} template(s)")
            else:
                templates = list(repo.rglob("*.template"))
                print(f"  [DRY RUN] Would render {len(templates)} template(s)")
        except Exception as e:
            print(f"  Template rendering: {e}")

        # Step 3: Run generate-templedb-inputs.py if it exists
        inputs_script = repo / 'generate-templedb-inputs.py'
        if inputs_script.exists():
            if not dry_run:
                import subprocess
                result = subprocess.run(
                    [sys.executable, str(inputs_script)],
                    cwd=str(repo), capture_output=True, text=True
                )
                if result.returncode == 0:
                    print(f"  Updated flake inputs")
                else:
                    print(f"  Flake inputs update failed: {result.stderr[:200]}")
            else:
                print(f"  [DRY RUN] Would run generate-templedb-inputs.py")

        # Step 4: Generate managed modules (existing generate logic)
        if not dry_run:
            import argparse
            gen_args = argparse.Namespace(
                slug=slug, output=None, cathedral_path=None,
                no_home_manager=False, include_templedb=True
            )
            print()
            self.generate(gen_args)
        else:
            print(f"  [DRY RUN] Would generate managed modules")

        # Step 5: Git stage generated files for nix eval
        if not dry_run:
            import subprocess
            subprocess.run(
                ["git", "add", "-A"],
                cwd=str(repo), capture_output=True
            )
            print(f"\n  Staged all generated files for nix evaluation")

        print(f"\nNext steps:")
        print(f"  templedb nixos rebuild {slug}")
        return 0


# ── Register ──────────────────────────────────────────────────────────────────

def register(cli):
    """Register NixOS commands with CLI"""
    cmd = NixOSCommand()

    nixos_parser = cli.register_command('nixos', None, help_text='NixOS integration and module generation')
    subparsers = nixos_parser.add_subparsers(dest='nixos_subcommand', required=True)

    # detect
    detect_parser = subparsers.add_parser('detect', help='Detect dependencies')
    detect_parser.add_argument('slug', help='Project slug')
    cli.commands['nixos.detect'] = cmd.detect

    # generate
    gen_parser = subparsers.add_parser('generate', help='Generate NixOS modules')
    gen_parser.add_argument('slug', help='Project slug')
    gen_parser.add_argument('-o', '--output', help='Output directory (default: auto)')
    gen_parser.add_argument('--cathedral-path', help='Path to existing Cathedral package')
    gen_parser.add_argument('--no-home-manager', action='store_true', help='Skip Home Manager module')
    gen_parser.add_argument('--include-templedb', action='store_true', default=True)
    gen_parser.add_argument('--no-templedb', dest='include_templedb', action='store_false')
    cli.commands['nixos.generate'] = cmd.generate

    # export
    export_parser = subparsers.add_parser('export', help='Export Cathedral package with NixOS modules')
    export_parser.add_argument('slug', help='Project slug')
    export_parser.add_argument('-o', '--output', help='Output directory')
    cli.commands['nixos.export'] = cmd.export

    # system-test
    test_parser = subparsers.add_parser('system-test', help='Test system configuration')
    test_parser.add_argument('slug', help='Project slug')
    test_parser.add_argument('--dry-run', action='store_true')
    cli.commands['nixos.system-test'] = cmd.system_test

    # update-input
    update_input_parser = subparsers.add_parser('update-input', help='Update a flake input')
    update_input_parser.add_argument('slug', help='Project slug')
    update_input_parser.add_argument('input', help='Flake input name')
    cli.commands['nixos.update-input'] = cmd.update_input

    # rebuild
    rebuild_parser = subparsers.add_parser('rebuild', help='Rebuild NixOS system')
    rebuild_parser.add_argument('slug', help='Project slug')
    rebuild_parser.add_argument('--dry-run', action='store_true')
    rebuild_parser.add_argument('--with-home-manager', action='store_true')
    rebuild_parser.add_argument('--update-input', metavar='INPUT')
    rebuild_parser.add_argument('--verbose', '-v', action='store_true')
    rebuild_parser.add_argument('--show-trace', action='store_true')
    rebuild_parser.add_argument('--yes', '-y', action='store_true')
    rebuild_parser.add_argument('--no-update-lock-file', dest='no_update_lock_file', action='store_true')
    cli.commands['nixos.rebuild'] = cmd.rebuild

    # system-switch
    switch_parser = subparsers.add_parser('system-switch', help='Switch to system configuration')
    switch_parser.add_argument('slug', help='Project slug')
    switch_parser.add_argument('--dry-run', action='store_true')
    switch_parser.add_argument('--with-home-manager', action='store_true')
    switch_parser.add_argument('--verbose', '-v', action='store_true')
    switch_parser.add_argument('--show-trace', action='store_true')
    switch_parser.add_argument('--yes', '-y', action='store_true')
    switch_parser.add_argument('--no-update-lock-file', dest='no_update_lock_file', action='store_true')
    cli.commands['nixos.system-switch'] = cmd.system_switch

    # system-status
    subparsers.add_parser('system-status', help='Show system deployment status')
    cli.commands['nixos.system-status'] = cmd.system_status

    # system-history
    history_parser = subparsers.add_parser('system-history', help='Show deployment history')
    history_parser.add_argument('--project', help='Filter by project')
    history_parser.add_argument('--limit', type=int, default=10)
    cli.commands['nixos.system-history'] = cmd.system_history

    # system-rollback
    rollback_parser = subparsers.add_parser('system-rollback', help='Rollback to previous deployment')
    rollback_parser.add_argument('deployment_id', type=int, nargs='?')
    cli.commands['nixos.system-rollback'] = cmd.system_rollback

    # set-type
    set_type_parser = subparsers.add_parser('set-type', help='Set project type')
    set_type_parser.add_argument('slug', help='Project slug')
    set_type_parser.add_argument('type', choices=['regular', 'nixos-config', 'service', 'library'])
    cli.commands['nixos.set-type'] = cmd.set_type

    # list-configs
    subparsers.add_parser('list-configs', help='List all nixos-config projects')
    cli.commands['nixos.list-configs'] = cmd.list_configs

    # nixos doctor command
    doctor_parser = subparsers.add_parser('doctor', help='Diagnose NixOS-config activation problems')
    doctor_parser.add_argument('slug', nargs='?', help='Limit checks to one project slug')
    cli.commands['nixos.doctor'] = cmd.doctor

    # config-get / config-set / config-list
    cg = subparsers.add_parser('config-get', help='Get system configuration value')
    cg.add_argument('key')
    cli.commands['nixos.config-get'] = cmd.config_get

    cs = subparsers.add_parser('config-set', help='Set system configuration value')
    cs.add_argument('key')
    cs.add_argument('value')
    cli.commands['nixos.config-set'] = cmd.config_set

    subparsers.add_parser('config-list', help='List all system configuration')
    cli.commands['nixos.config-list'] = cmd.config_list

    # add-package / remove-package / list-packages
    ap = subparsers.add_parser('add-package', help='Add CLI tool to managed packages')
    ap.add_argument('slug')
    ap.add_argument('--scope', choices=['system', 'user'], default='user')
    ap.add_argument('--flake-uri')
    ap.add_argument('--name')
    ap.add_argument('--version')
    cli.commands['nixos.add-package'] = cmd.add_package

    rp = subparsers.add_parser('remove-package', help='Remove CLI tool from managed packages')
    rp.add_argument('slug')
    cli.commands['nixos.remove-package'] = cmd.remove_package

    lp = subparsers.add_parser('list-packages', help='List all managed packages')
    lp.add_argument('--scope', choices=['system', 'user'])
    cli.commands['nixos.list-packages'] = cmd.list_packages

    # status (pipeline status)
    status_p = subparsers.add_parser('status', help='Show full pipeline state')
    status_p.add_argument('slug', nargs='?', help='NixOS config project slug (auto-detect)')
    cli.commands['nixos.status'] = cmd.nixos_status

    # edit-template
    et = subparsers.add_parser('edit-template', help='Open .nix.template files in $EDITOR')
    et.add_argument('slug', nargs='?', help='NixOS config project slug (auto-detect)')
    cli.commands['nixos.edit-template'] = cmd.nixos_edit_template

    # dotfiles-apply
    da = subparsers.add_parser('dotfiles-apply', help='Apply dotfile symlinks from manifest')
    da.add_argument('--force', '-f', action='store_true', help='Replace existing files')
    da.add_argument('--verbose', '-v', action='store_true', help='Show already-OK links')
    cli.commands['nixos.dotfiles-apply'] = cmd.dotfiles_apply

    # dotfiles-add
    dadd = subparsers.add_parser('dotfiles-add', help='Add dotfile mapping')
    dadd.add_argument('project', help='Project slug (e.g. system_config)')
    dadd.add_argument('source', help='Relative path in checkout (e.g. .spacemacs)')
    dadd.add_argument('target', help='Target path (e.g. ~/.spacemacs)')
    cli.commands['nixos.dotfiles-add'] = cmd.dotfiles_add

    # dotfiles-remove
    drm = subparsers.add_parser('dotfiles-remove', help='Remove dotfile mapping')
    drm.add_argument('project', help='Project slug')
    drm.add_argument('source', help='Relative path in checkout')
    cli.commands['nixos.dotfiles-remove'] = cmd.dotfiles_remove

    # dotfiles-list
    dl = subparsers.add_parser('dotfiles-list', help='List dotfile mappings and status')
    cli.commands['nixos.dotfiles-list'] = cmd.dotfiles_list

    # import-config
    ic = subparsers.add_parser('import-config', help='Import existing NixOS config into DB')
    ic.add_argument('slug', nargs='?', help='NixOS config project slug')
    cli.commands['nixos.import-config'] = cmd.import_config

    # generate-all
    ga = subparsers.add_parser('generate-all', help='Generate all NixOS config from DB (templates + modules + inputs)')
    ga.add_argument('slug', nargs='?', help='NixOS config project slug')
    ga.add_argument('--host', help='Generate for specific host (default: active host from nixos.flake_output)')
    ga.add_argument('--dry-run', action='store_true', help='Show what would be generated')
    cli.commands['nixos.generate-all'] = cmd.generate_all

    # host subcommands
    hl = subparsers.add_parser('host', help='Manage NixOS host configurations')
    host_sub = hl.add_subparsers(dest='host_command', required=True)

    hlist = host_sub.add_parser('list', help='List all hosts')
    cli.commands['nixos.host.list'] = cmd.host_list

    hshow = host_sub.add_parser('show', help='Show host-specific config')
    hshow.add_argument('hostname', help='Host name')
    cli.commands['nixos.host.show'] = cmd.host_show

    hset = host_sub.add_parser('set', help='Set host-scoped config override')
    hset.add_argument('hostname', help='Host name')
    hset.add_argument('key', help='Config key (will be prefixed with hostname.)')
    hset.add_argument('value', help='Config value')
    cli.commands['nixos.host.set'] = cmd.host_set

    himp = host_sub.add_parser('import', help='Import host-specific values from .nix file')
    himp.add_argument('hostname', help='Host name')
    himp.add_argument('slug', nargs='?', help='NixOS config project slug')
    cli.commands['nixos.host.import'] = cmd.host_import

    hact = host_sub.add_parser('activate', help='Set this machine to a host')
    hact.add_argument('hostname', help='Host name to activate')
    cli.commands['nixos.host.activate'] = cmd.host_activate

    hclone = host_sub.add_parser('clone', help='Clone host config to a new hostname')
    hclone.add_argument('source', help='Source host to clone from')
    hclone.add_argument('target', help='New host name')
    cli.commands['nixos.host.clone'] = cmd.host_clone
